-- Initial schema
CREATE TABLE IF NOT EXISTS users (
	id BIGINT PRIMARY KEY NOT NULL UNIQUE,
	username VARCHAR(32) UNIQUE NOT NULL,
	display_name VARCHAR(32),
	bio VARCHAR(2048),
	permissions BIGINT NOT NULL DEFAULT 0,
	flags BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS messages (
	id BIGINT PRIMARY KEY NOT NULL UNIQUE,
	author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	content VARCHAR(4048),
	thread_id BIGINT NOT NULL,
	referenced_message_id BIGINT REFERENCES messages(id) ON DELETE SET NULL,
	flags BIGINT NOT NULL DEFAULT 0,
	updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS categories (
	id BIGINT PRIMARY KEY NOT NULL UNIQUE,
	owner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
	title VARCHAR(128) NOT NULL,
	description VARCHAR(2048) NOT NULL
);

CREATE TABLE IF NOT EXISTS threads (
	id BIGINT PRIMARY KEY NOT NULL UNIQUE,
	title VARCHAR(128),
	author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	original_message_id BIGINT NOT NULL UNIQUE REFERENCES messages(id) ON DELETE CASCADE,
	likes INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE messages
ADD CONSTRAINT fk_messages_thread
FOREIGN KEY (id) REFERENCES threads(id) ON DELETE CASCADE;

